### ISSUE TITLE
Comparison to wgrep

### ISSUE THREAD

**Issue by CeleritasCelery** [tyler-dodge/counsel-edit-mode#1]
How does this package compare to [wgrep](https://github.com/mhayashi1120/Emacs-wgrep), which seems to do something similar? From a counsel search you can use `C-c C-o` to open an occur buffer. From there you can use `C-c C-p` to switch to wgrep mode (if the package is installed).

**Comment by tyler-dodge** [comment]
I hadn't tried wgrep until just now, but there are a few important differences:
* counsel-edit-mode represents the the page and line number as an overlay instead of as text in the buffer. This has the benefit of making it so that structured editing can still work correctly while in the buffer since the text operations don't see the UI.
* The major mode is overridable in the edit buffer, which makes it easier to work with specific language modes while doing transformations across the buffer
* counsel-edit-mode-expand-braces-by-default makes it so that you can expand the context in an area so that there are no unmatched parens in the search buffer. There is also a command called counsel-edit-mode-expand-section which expands the section at point.

**Comment by CeleritasCelery** [comment]
Thanks! Could be useful to include this in the README.
